// Generated by https://quicktype.io

export interface PokemonTable {
  count:    number;
  next:     string;
  previous: string;
  results:  PokemonData[];
}

export interface PokemonData {
  name: string;
  url:  string;
  onEdition?: boolean;
}
